% Run using
% roast_and_brew_plates('../small_test/plate_list.grp','/cmap/users/jnasser/dpeak_v2/small_test2')


function roast_and_brew_plates(plate,plate_path)

cd /cmap/users/jnasser/code/espresso/

%% Roast the plates
roast('plate',fullfile(plate_path,plate), ...
  'plate_path',plate_path, ...
  'raw_path','/cmap/obelix/pod/custom/REP/lxb', ...
  'map_path','/cmap/obelix/pod/custom/REP/maps',...
  'detect_param','/cmap/users/jnasser/dpeak_v2/detect_params_jn.txt',...
  'flip_correct',true,...
  'usecount',false,...
  'codes','/cmap/users/jnasser/dpeak_v2/process_codes_jn.txt',...
  'overwrite',true)

%% Brew the plates
brew('plate',fullfile(plate_path,plate),...
        'plate_path',plate_path, ...
        'brew_path',plate_path, ...
        'group_by', 'rna_well', ...
        'zmad_ref', 'ZSPC', ...
        'filter_vehicle', false,...
        'overwrite',true)

%% Compute dpeak suspiciousness
% brew_ds = parse_gctx(ls(fullfile(plate_path,'*MODZ)));
% roast_ds = parse_gctx('/cmap/users/jnasser/dpeak_v2/small_test/REP.A010_A375_24H/REP.A010_A375_24H_ZSPCQNORM_n1087x978.gctx');
% suspA = compute_misscall_suspects_per_brew_gene(...
%     brew_ds,roast_ds);
% 
% brew_ds = parse_gctx('/cmap/users/jnasser/dpeak_v2/small_test/REP.A010_A375_24H/by_rna_well/REP.A010_A375_24H_COMPZ.MODZ_SCORE_LM_n375x978.gctx');
% roast_ds = parse_gctx('/cmap/users/jnasser/dpeak_v2/small_test/REP.A010_A375_24H/REP.A010_A375_24H_ZSPCQNORM_n1087x978.gctx');
% suspA = compute_misscall_suspects_per_brew_gene(...
%     brew_ds,roast_ds);

% %% Compute dpeak suspiciousness
% brew_ds = parse_gctx('/cmap/users/jnasser/dpeak_v2/small_test/REP.B010_A375_24H/by_rna_well/REP.B010_A375_24H_COMPZ.MODZ_SCORE_LM_n375x978.gctx');
% roast_ds = parse_gctx('/cmap/users/jnasser/dpeak_v2/small_test/REP.B010_A375_24H/REP.B010_A375_24H_ZSPCQNORM_n1087x978.gctx');
% suspB = compute_misscall_suspects_per_brew_gene(...
%     brew_dsB,roast_dsB);
end